name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image from the Dockerfile
      - name: Build Docker image
        run: docker build -t selenium-tests .

      # Run Docker container with the built image
      - name: Run Selenium tests
        run: docker run selenium-tests
